### ISSUE TITLE
Picar algo sencillo con genéticos

### ISSUE THREAD

**Issue by 29antonioac** [analca3/TFG#2]
Debería escribir algo sencillo con genéticos para interiorizar todo lo leído.

**Comment by JJ** [comment]
Ya puestos hazlo en un nuevo lenguaje. Go, por ejemplo. O Groovy. O ayúdame con la librería en Scala, que está muy básica (sólo tiene mutación y crossover)

**Comment by 29antonioac** [comment]
Aquí en Go https://github.com/analca3/Go-Genetic

Si os sirve para https://github.com/geneura-papers/2015-ea-languages , perfecto :). A ver si el viernes pruebo Groovy. Scala lo miraré el finde si tengo un hueco.

**Comment by JJ** [comment]
Groovy mejor, aunque si miras lo qeu está hecho en Scala, también. Prueba también esta función http://104.131.4.62/ que tiene tela, la Rastrigin.

**Comment by 29antonioac** [comment]
https://github.com/analca3/Groovy-genetic

A ver si saco un hueco para Scala...

**Comment by JJ** [comment]
Si quieres mirar lo que yo he hecho ya y mejorarlo...

Genial lo de Groovy

**Comment by 29antonioac** [comment]
El problema de Groovy es que es lentísimo. Lo que tarda no es normal, no sé si será por haber tomado el camino de scripting, por usar variables no tipadas... Pero me parece demasiado lento.

**Comment by JJ** [comment]
¿Se puede compilar?

2015-11-11 9:42 GMT+01:00 Antonio Álvarez Caballero <
notifications@github.com>:

> El problema de Groovy es que es lentísimo. Lo que tarda no es normal, no
> sé si será por haber tomado el camino de scripting, por usar variables no
> tipadas... Pero me parece demasiado lento.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/analca3/TFG/issues/2#issuecomment-155705241.

## 

JJ

**Comment by 29antonioac** [comment]
Sí, pero es lo mismo. De hecho, aunque se escriba y ejecute como script, él mismo lo compila al ejecutar, siempre.

http://www.groovy-lang.org/structure.html#_script_class

**Comment by JJ** [comment]
Habrá que mirarlo de todas formas...

2015-11-11 10:14 GMT+01:00 Antonio Álvarez Caballero <
notifications@github.com>:

> Sí, pero es lo mismo. De hecho, aunque se escriba y ejecute como script,
> él mismo lo compila al ejecutar, siempre.
> 
> http://www.groovy-lang.org/structure.html#_script_class
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/analca3/TFG/issues/2#issuecomment-155711131.

## 

JJ

**Comment by JJ** [comment]
¿se cierra?

**Comment by 29antonioac** [comment]
Sí
