### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by iblancasa** [analca3/TFG#8]
Primero de todo, añade en el README que lo que se quiere compilar es la memoria y que está en el directorio "Memoria".

Yo te recomendaría hacer varias reglas para el makefile:
- Una regla para el Rnw
- Otra para el PDF
- Otra para el .bib

De esa forma, cuando ejecutes `make` solo recompilarás lo que haya cambiado (ahorrando bastante tiempo). Como compiles todo cada vez que cambies algo... vas a echar la vida.

También vendría bien un make install que te instalara R y las dependencias que usas (para no tener que hacerlo a mano)

**Comment by 29antonioac** [comment]
Gracias!

https://github.com/analca3/TFG/commit/e9735afaa2a2641aa5b2306ce25cc113cebf9083
